#!/usr/bin/env sh

# Initially from:
# https://stackoverflow.com/questions/20479794/how-do-i-properly-git-stash-pop-in-pre-commit-hooks-to-get-a-clean-working-tree

# Stash all uncommited changes
old_stash=$(git rev-parse -q --verify refs/stash)
git stash --keep-index --include-untracked -q
new_stash=$(git rev-parse -q --verify refs/stash)

# Format all nix files in my repo and add the changes
nix fmt -- ~/dots/**/*.nix
git add -A

# Try to apply stashed changes, but only if there were any
if [ "$old_stash" != "$new_stash" ]; then
  git stash pop -q
fi
