#!/usr/bin/env bash
set -euo pipefail
shopt -s globstar nullglob # for ** expanding

# Save staged changes into a temporary commit
TMP_MSG="pre-commit-$(date +%s)"
git commit --no-verify -m "$TMP_MSG" >/dev/null 2>&1

# Stash all the unstaged changes that are left
git stash --include-untracked -q -m "$TMP_MSG"
# git stash --keep-index --include-untracked -q -m "$TMP_MSG"

# Reset HEAD to undo commit, but keep staged files staged
git reset --soft HEAD^ >/dev/null 2>&1

nix fmt -- "$HOME"/dots/**/*.nix # format all nix files
git add -u # stage only existing files

# Try to apply stashed changes, but only if there were any
if git stash list | grep -q "$TMP_MSG"; then
  git stash pop -q
fi
