#!/bin/bash
# vim:set ts=4 sw=4:

set -e

sudo pacman -Syu

# fixing the fastest antergos servers
# sudo rankmirrors -n 0 /etc/pacman.d/antergos-mirrorlist > /tmp/antergos-mirrorlist && sudo cp /tmp/antergos-mirrorlist /etc/pacman.d

# installing refector to test wich servers are fastest
# sudo pacman -S --noconfirm --needed reflector
# sudo reflector --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist

# install xorg and i3-gaps
sudo pacman -S xorg xorg-server xorg-apps xorg-xinit xorg-twm xterm i3-gaps --noconfirm --needed

# autologin on start
sudo cp settings/autologin@.service /etc/systemd/system/
sudo ln -sf /etc/systemd/system/autologin@.service /etc/systemd/system/getty.target.wants/getty@tty1.service
sudo systemctl enable autologin@tty1.service
sudo systemctl start autologin@tty1.service

# install packages from pacman
sudo pacman -S --noconfirm --needed curl vlc git gparted htop screenfetch ranger wget unclutter zip unzip gnome-keyring libsecret
sudo pacman -S --noconfirm --needed termite keepassx2 gvim feh dunst xautolock xclip xdotool xbindkeys the_silver_searcher scrot
sudo pacman -S --noconfirm --needed udiskie transmission-gtk ttf-dejavu rofi nodejs npm ctags tmux lxappearance perl-file-mimeinfo
sudo pacman -S --noconfirm --needed alsa-firmware alsa-utils alsa-plugins pulseaudio-alsa pulseaudio

# install packages from yaourt
yaourt -S --noconfirm zsh oh-my-zsh-git bullet-train-oh-my-zsh-theme-git i3lock-fancy-git spotify jdk8
yaourt -S --noconfirm ttf-font-awesome-4 gtk-theme-arc-grey-git skypeforlinux-stable-bin google-chrome watchman

# set zsh as default shell
chsh -s /bin/zsh
