#!/usr/bin/env zsh
# vim:set ts=4 sw=4:

main () {
    echo "~/dotfiles -> ~/ are you sure? [y/n]: \c"
    read line
    if [[ "$line" == y* ]]; then
        echo "Installing main dotfiles"
        rm -fr ~/.vim
        rm ~/.agignore ~/.ctags ~/.gitconfig ~/.gitignore ~/.importjs.js ~/.tmux.conf ~/.vimrc ~/.zshrc

        mkdir ~/dotfiles/.vim/undo
        mkdir ~/dotfiles/.vim/session

        ln -s ~/dotfiles/.agignore ~/.agignore
        ln -s ~/dotfiles/.ctags ~/.ctags
        ln -s ~/dotfiles/.gitconfig ~/.gitconfig
        ln -s ~/dotfiles/.gitignore ~/.gitignore
        ln -s ~/dotfiles/.importjs.js ~/.importjs.js
        ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
        ln -s ~/dotfiles/.vim ~/.vim
        ln -s ~/dotfiles/.vimrc ~/.vimrc
        ln -s ~/dotfiles/.zshrc ~/.zshrc
        ln -s ~/dotfiles/.prettierrc.json ~/.prettierrc
}

main
